export const ALL_POSTS = 'ALL_POSTS'
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS'

export const POST_BY_CATEGORY= 'POST_BY_CATEGORY'
export const POST_BY_CATEGORY_SUCCESS = 'POST_BY_CATEGORY_SUCCESS'


export const POST_DETAIL = 'POST_DETAIL'
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS'

export const ALL_CATEGORIES = 'ALL_CATEGORIES'
export const CATEGORY_DETAIL = 'CATEGORY_DETAIL'


export const GET_DBFILE = 'GET_DBFILE'
export const SET_DBFILE = 'SET_DBFILE'
